server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice  #userservice服务的服务名称
  cloud:
    nacos:
      server-addr:  localhost:8848 #nacos服务地址
      discovery:
        cluster-name: HZ #配置集群名称， 也就是机房位置，例如：HZ,杭州
        namespace: 1789c298-ba96-4e93-bfdb-75ce0b77038b
## mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:com/cl/user/mapper/**/*.xml # 扫描xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志打印

## eureka配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

